spring:
  application:
    name: greensea
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      #    password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          #数据库驱动完整类名
          driver-class-name: com.mysql.cj.jdbc.Driver
          #数据库连接url
          url: jdbc:mysql://47.113.192.133:3306/greensea_device
          #数据库用户名
          username: root
          # druid 连接池管理
          password: greensea123456
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.113.192.133:3306/greensea_energy
          username: root
          password: greensea123456
  # 文件配置
  servlet:
    multipart:
      enabled: true
      # 文件单个限制
      max-file-size: 1MB
      # 请求最大限制
      max-request-size: 20MB


server:
  port: 8082
# springdoc-openapi项目配置，访问地址：http://127.0.0.1:8081/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '框架'
      paths-to-match: '/**'
      packages-to-scan: greensea.energy.upload.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    #  basic:
    #    enable: true
    # Basic账号
    #    username: root
    # Basic密码
#    password: 123456

mybatis-plus:
  global-config:
    db-config:
      # 主键类型：自增
      id-type: ASSIGN_ID
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 6 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # mapper xml文件路径
  mapper-locations: classpath:mapper/*.xml


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: tyutselabababbaaabcdefghijklmnopqrstuvwxyzaaaaaaaaaaaaa32136758967
  # 令牌有效期（单位分钟）
  expireTime: 1440

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10


# Logger Config
logging:
  level:
    com.hexadecimal: debug